# Generated by Django 3.0.3 on 2020-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200)),
                ('starting_date', models.DateTimeField(verbose_name='Starting Date')),
                ('ending_date', models.DateTimeField(verbose_name='Ending Date')),
                ('is_current_work', models.BooleanField()),
            ],
        ),
    ]
